/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.gestionproductos.vista;

import ec.edu.espoch.gestiontareas.controlador.Controlador;
import ec.edu.espoch.gestiontareas.tester.TesterVista;

/**
 *
 * @author jordy
 */
public class Principal extends javax.swing.JFrame {
    private Controlador controlador;
    private ListarIU listarIU;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.listarIU= new ListarIU();
        this.controlador = new Controlador(this, listarIU);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupEstado = new javax.swing.ButtonGroup();
        lbdTitulo = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        textAreaAgregar = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lbdError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuListar = new javax.swing.JMenu();
        menuItemListar = new javax.swing.JMenuItem();
        jmenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbdTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbdTitulo.setText("Sistema Gestion de Productos");

        lblAgregar.setText("Agregar Productos:");

        lblDescripcion.setText("Descripcion:");

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(textAreaDescripcion);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbdError.setText("--------------");

        jmenuListar.setText("Listar");

        menuItemListar.setText("Listar Productos");
        menuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarActionPerformed(evt);
            }
        });
        jmenuListar.add(menuItemListar);

        jMenuBar1.add(jmenuListar);

        jmenuSalir.setText("Salir");
        jMenuBar1.add(jmenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgregar)
                        .addGap(53, 53, 53)
                        .addComponent(textAreaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lbdTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnRegistrar)
                        .addGap(80, 80, 80)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lbdError)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbdTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregar)
                    .addComponent(textAreaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegistrar))
                .addGap(28, 28, 28)
                .addComponent(lbdError)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        this.controlador.registraProducto(); 
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void menuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarActionPerformed
        // TODO add your handling code here:
        listarIU.setVisible(true);
        controlador.listarProducto();
    }//GEN-LAST:event_menuItemListarActionPerformed
    
    public String getTitulo(){
        return textAreaAgregar.getText();
    }
    
    public String getDescripcion(){
        return textAreaDescripcion.getText();
    }
       public String getDisponible(){
        return textAreaDescripcion.getText();
    }
    
    public void error(String text){
        lbdError.setText(text);
    }
    
    public void limpiar(){
    
    textAreaAgregar.setText("");
    textAreaDescripcion.setText("");
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupEstado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmenuListar;
    private javax.swing.JMenu jmenuSalir;
    private javax.swing.JLabel lbdError;
    private javax.swing.JLabel lbdTitulo;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JMenuItem menuItemListar;
    private javax.swing.JTextField textAreaAgregar;
    private javax.swing.JTextArea textAreaDescripcion;
    // End of variables declaration//GEN-END:variables

    public String getNombre() {
        
        return null;
        
    }

    public String getPrecio() {
   
        return null;
   
    }


    public boolean isDisponible() {
        return false;
    }


}
